Fix: Change network value from mainnet to regtest
libsv/go-p4 pull request #26
Opened 2021-10-06 09:41 UTC by tigh-latte

Currently in testing the payment body says `"network": "mainnet"` on regtest.

2021-10-06 09:57 UTC, theflyingcodr requested changes
Think network should come from PayD - possibly from the destinations endpoint

2021-10-06 09:57 UTC, theflyingcodr commented on service/paymentrequest.go
> +		Network:             string(p.deployCfg.Network),
This should probably come from payd actually rather than being set on P4, this has been something on my internal backlog to fix but hadn't got round to it yet.

2021-10-06 10:03 UTC, Tigh-Gherr commented on service/paymentrequest.go
> +		Network:             string(p.deployCfg.Network),
So should payd be dumb to the network it's running against as well?

2021-10-07 08:52 UTC, theflyingcodr approved these changes
LGTM

2021-10-07 08:53 UTC, merged