Updates to `PaymentRequest` stuctures to align with the latest TSC spec.
libsv/go-p4 pull request #69
Opened 2022-07-28 09:30 UTC by AustEcon

As discussed with @jadwahab and @sirdeggen here is the PR for updating to the TSC spec: https://tsc.bitcoinassociation.net/standards/direct_payment_protocol/

So far this only updates the `PaymentRequest` structure which is enough for now to get ElectrumSV through the first part of the data flow for development...

Still to do:

- [ ] `Payment`
- [ ] `PaymentACK`

Until the `dpp-proxy` is updated to the TSC spec, ElectrumSV will be building against this feature branch to avoid technical debt of the old message structures. So if you are not a fan of this implementation, that is no problem - it still unblocks Roger and I to keep progressing the ElectrumSV integration until the dpp-proxy master branch catches up. 😃

2022-07-28 15:56 UTC, jadwahab commented on payment_request.go
>  type PaymentRequest struct {
also shouldn't this be renamed to `PaymentTerms`? 🤔

2022-07-29 04:12 UTC, AustEcon commented on payment_request.go
>  type PaymentRequest struct {
Yes. You are right. I will change it

2022-07-30 14:39 UTC, jadwahab commented on payment_request.go
>  type PaymentRequestReader interface {
shouldn't all places where we have PaymentRequest be PaymentTerms instead?

2022-07-30 14:41 UTC, jadwahab requested changes
I think we should have different folders/modules for different payment modes, what do you think? would be worth asking @theflyingcodr

2022-08-01 09:54 UTC, AustEcon commented on payment_request.go
>  type PaymentRequestReader interface {
Yes. I suppose it should. I have now updated all instances of `PaymentRequest` to `PaymentTerms` for go-dpp and the dpp-proxy.

This includes the websocket message types: `paymentterms.create`, `paymentterms.response` and `paymentterms.error`

For consistency.

2022-08-01 10:02 UTC, AustEcon commented
> I think we should have different folders/modules for different payment modes, what do you think? would be worth asking @theflyingcodr

I have refactored the three DPP message types into a `messages` package with:
- `hybrid_payment_terms.go`
- `hybrid_payment.go`
- `hybrid_payment_ack.go`

The reason I shied away from nesting it any further is because I personally prefer when I am using a library (in the dpp-proxy) that the code completion groups and lists out all of the relevant structs when I type `messages. `

I think it's more intuitive when you see something like:
![image](https://user-images.githubusercontent.com/8123976/182124435-37927285-834c-4ad5-b65d-2f7b8a876463.png)

2022-09-01 21:54 UTC, sirdeggen commented
Still discussing, sorry @AustEcon - early next week should have resolved the differences in opinion on this.

2023-10-19 12:55 UTC, closed without merging